name: Los 2 Lados del Billete
favicon: null
layout_spectrum: 0.76124
typography_spectrum: 0.48164863628335297
title: 'Todo es sobre economía '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
