name: Los 2 Lados de la Moneda
favicon: null
layout_spectrum: 0.837489154888317
typography_spectrum: 0.48164863628335297
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3084156676195562
  lightness: 0.7220020084641874
  saturation: 0.194222129881382
  rhythmicContrast: 0.0713184759952128
purpose: []
